owner: jainish2001 
repo: rishabhdeo-com-status

sites:
  - name: Rishabhdeo Temple Website
    url: https://www.rishabhdeo.com

status-website:
  cname: status.rishabhdeo.com
  logoUrl: https://raw.githubusercontent.com/jainish2001/rishabhdeo-com-status/refs/heads/master/assets/rishabhdeo_bhagwan.jpg
  favicon: https://raw.githubusercontent.com/jainish2001/rishabhdeo-com-status/refs/heads/master/assets/favicon.ico
  name: Rishabhdeo Temple
  introTitle: "**Live Infrastructure Status**"
  introMessage: Real-time monitoring for the official Shri Rishabhdeo Temple website.
  navbar:
    - title: Status
      href: /
    - title: Back to Temple Site
      href: https://www.rishabhdeo.com/


i18n:
  activeIncidents: "Active Incidents | सक्रिय घटनाएँ"
  allSystemsOperational: "All Systems Operational | सभी सिस्टम सुचारू रूप से काम कर रहे हैं"
  incidentReport: "Incident Report | घटना रिपोर्ट"
  activeIncidentSummary: "There are currently $ACTIVE_INCIDENTS active incidents. | वर्तमान में $ACTIVE_INCIDENTS सक्रिय घटनाएँ हैं।"
  down: "Down | बंद"
  up: "Up | चालू"
  
  
