owner: jainish2001 
repo: rishabhdeo-com-status

sites:
  - name: Rishabhdeo Temple Website
    url: https://www.rishabhdeo.com

status-website:
  cname: status.rishabhdeo.com
  logourl: https://raw.githubusercontent.com/jainish2001/rishabhdeo-com-status/refs/heads/master/assets/rishabhdeo_bhagwan.jpg
  favicon: https://raw.githubusercontent.com/jainish2001/rishabhdeo-com-status/refs/heads/master/assets/favicon.ico
  name: Rishabhdeo Temple - Site Status
  introTitle: "**Live Infrastructure Status**"
  introMessage: Real-time monitoring for the official Shri Rishabhdeo Temple digital services.
  navbar:
    - title: Status
      href: /
    - title: Back to Temple Site
      href: https://www.rishabhdeo.com/
  removeFooter: true 
  customFooter: |
      <div style="text-align: center; font-size: 0.9rem; padding: 10px 0;">
        <strong>SITE DEVELOPED AND MAINTAINED BY <a href="https://maps.app.goo.gl/sHscF6XJnNCJXUSe7" target="_blank" style="color: #991F61; text-decoration: none;">PRIYA ELECTRONICS, RISHABHDEO</a></strong>
        <br/>
        ✉️ <a href="mailto:contact@jainishjain.com" style="color: inherit; text-decoration: none;">contact@jainishjain.com</a>
      </div>

i18n:
  activeIncidents: "Active Incidents | सक्रिय घटनाएँ"
  allSystemsOperational: "All Systems Operational | सभी सिस्टम सुचारू रूप से काम कर रहे हैं"
  incidentReport: "Incident Report | घटना रिपोर्ट"
  activeIncidentSummary: "There are currently $ACTIVE_INCIDENTS active incidents. | वर्तमान में $ACTIVE_INCIDENTS सक्रिय घटनाएँ हैं।"
  down: "Down | बंद"
  up: "Up | चालू"
  
  
